// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ContactNo struct {
	_tab flatbuffers.Struct
}

func (rcv *ContactNo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ContactNo) Table() flatbuffers.Table {
	return rcv._tab.Table
}

func (rcv *ContactNo) CountryCode() int8 {
	return rcv._tab.GetInt8(rcv._tab.Pos + flatbuffers.UOffsetT(0))
}
func (rcv *ContactNo) MutateCountryCode(n int8) bool {
	return rcv._tab.MutateInt8(rcv._tab.Pos+flatbuffers.UOffsetT(0), n)
}

func (rcv *ContactNo) Number() uint64 {
	return rcv._tab.GetUint64(rcv._tab.Pos + flatbuffers.UOffsetT(8))
}
func (rcv *ContactNo) MutateNumber(n uint64) bool {
	return rcv._tab.MutateUint64(rcv._tab.Pos+flatbuffers.UOffsetT(8), n)
}

func CreateContactNo(builder *flatbuffers.Builder, countryCode int8, number uint64) flatbuffers.UOffsetT {
	builder.Prep(8, 16)
	builder.PrependUint64(number)
	builder.Pad(7)
	builder.PrependInt8(countryCode)
	return builder.Offset()
}
