// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

type Gender = int8
const (
	GenderMALE Gender = 1
	GenderFEMALE Gender = 2
	GenderTRANSGENDER Gender = 3
	GenderNOT_SPECIFIED Gender = 4
)

var EnumNamesGender = map[Gender]string{
	GenderMALE:"MALE",
	GenderFEMALE:"FEMALE",
	GenderTRANSGENDER:"TRANSGENDER",
	GenderNOT_SPECIFIED:"NOT_SPECIFIED",
}

