CREATE DATABASE init;
CREATE TABLE apps(ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,NAME VARCHAR(250) NOT NULL,EMAIL VARCHAR(250) NOT NULL,DOMAIN VARCHAR(250) NOT NULL,CONTACT VARCHAR(15) NOT NULL,RSAPUBKEY TEXT)

